CREATE TABLE IF NOT EXISTS user (
	id		INT NOT NULL AUTO_INCREMENT,
	name		VARCHAR(255) NOT NULL UNIQUE,
	password	VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS token (
	id		INT NOT NULL AUTO_INCREMENT,
	uid		INT NOT NULL,
	passphrase	VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS storage (
	id 		INT NOT NULL AUTO_INCREMENT,
	filename	VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS spot (
	id		BIGINT NOT NULL AUTO_INCREMENT,
	uid		INT NOT NULL,
	latitude	DOUBLE NOT NULL,
	longitude	DOUBLE NOT NULL,
	time		TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS picture (
	id		INT NOT NULL AUTO_INCREMENT,
	spotid		BIGINT,
	storageid	INT NOT NULL,
	pgroupid	INT,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS pgroup (
	id		INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comment (
	id		BIGINT NOT NULL AUTO_INCREMENT,
	uid		INT NOT NULL,
	content		TEXT NOT NULL,
	time		TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	pgroupid	INT NOT NULL,
	PRIMARY KEY (id)
);
