CREATE TABLE user (
	id		INT NOT NULL AUTO_INCREMENT,
	name		VARCHAR(255) NOT NULL UNIQUE,
	password	VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE token (
	id		INT NOT NULL AUTO_INCREMENT,
	uid		INT NOT NULL,
	passphrase	VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);
