CREATE TABLE IF NOT EXISTS user (
	id		INT NOT NULL AUTO_INCREMENT,
	name		VARCHAR(255) NOT NULL UNIQUE,
	password	VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS token (
	id		INT NOT NULL AUTO_INCREMENT,
	uid		INT NOT NULL,
	passphrase	VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS storage (
	id 		INT NOT NULL AUTO_INCREMENT,
	filename	VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (id)
);
